#!/bin/bash

set +e

product_dir=rcontrol

mkdir -p /home/${SUDO_USER}/.config/$product_dir

chown -R ${SUDO_USER}:${SUDO_USER}  /home/${SUDO_USER}/.config/$product_dir
chmod -R ug=rwX,o=rX                /home/${SUDO_USER}/.config/$product_dir

exit 0
