#!/bin/bash

set +e

product_dir=rcontrol
group_name=rcontrol

service_name=rcontrolagent

#udevadm control --reload-rules

#
# Регистрация systemd-сервиса

#
sed -e "s/%TARGET_USER%/$SUDO_USER/" \
    -i /etc/systemd/system/${service_name}.service

need_reboot=

#
# Создание пользовательских групп
#
#--- Group '$group_name' ---
res=$(cat /etc/group | grep "$group_name")
if [ -z "$res" ]; then
    groupadd -f $group_name
    echo "The group $group_name is created"
fi

res=$(groups $SUDO_USER | grep "$group_name")
if [ -z "$res" ]; then
    usermod -aG $group_name $SUDO_USER
    need_reboot=yes
fi

if [ "$need_reboot" = "yes" ]; then
    echo "====================================================== "
    echo "! The user $SUDO_USER added to groups: ${group_name}.  "
    echo "! Need relogin user and repeat installation.           "
    echo "====================================================== "
    exit 1
fi

#
# Назначение прав на рабочие директории
#
chown -R root:$group_name  /etc/$product_dir
chmod -R ug=rwX,o=rX       /etc/$product_dir

chown -R root:$group_name  /var/opt/$product_dir
chmod -R ug=rwX,o=rX       /var/opt/$product_dir

contains=$(sudo cat /etc/sudoers | grep '%sudo ALL=(ALL:ALL) NOPASSWD: /sbin/reboot, /usr/bin/nvidia-settings, /usr/bin/nvidia-smi')
if [[ -z $contains ]]; then
    echo '%sudo ALL=(ALL:ALL) NOPASSWD: /sbin/reboot, /usr/bin/nvidia-settings, /usr/bin/nvidia-smi' | sudo tee -a /etc/sudoers
fi

sudo nvidia-xconfig --cool-bits=28 --enable-all-gpus --allow-empty-initial-configuration 

systemctl daemon-reload

systemctl unmask ${service_name}.service
systemctl enable ${service_name}.service
systemctl start  ${service_name}.service

exit 0
