#!/bin/bash

set +e

service_name=rcontrolagent

systemctl daemon-reload

res=$(systemctl list-unit-files | grep "$service_name")
if [ -n "$res" ]; then
    systemctl stop    ${service_name}.service
    systemctl disable ${service_name}.service
fi

exit 0
